### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by david-shortman** [MountainSOLSchool/platform#16]
- [x] admin protected routes
- [x] workflow "next" disabled
- [x] student info form
- [x] class cart
- [x] confirmation
- [x] enroll in database
- [x] show enrollment in user profile
- [x] reset password in user profile
- [x] receipt email

**Comment by david-shortman** [comment]
donezo-ish
